### ISSUE TITLE
Github page를 만들어 확인할수 있게 합니다.

### ISSUE THREAD

**Issue by LeeJehwan** [Alpha-ka-JS/HTML-CSS-ARTIST#7]
일단 root로 page 만들어놨습니다. 
> https://alpha-ka-js.github.io/HTML-CSS-ARTIST/

inext.html이 없어서 아무것도 뜨지 않을것 입니다. 

일단은 도메인으로 접근해야 static page를 볼 수 있습니다. 
> https://alpha-ka-js.github.io/HTML-CSS-ARTIST/leejehwan/chpater2/2.10.Semantic_HTML.html

이후 index.html 생성 -> 각 user별 link or navigation bar 만들기

**Comment by LeeJehwan** [comment]
> 일단 root로 page 만들어놨습니다.
> 
> > https://alpha-ka-js.github.io/HTML-CSS-ARTIST/
> 
> inext.html이 없어서 아무것도 뜨지 않을것 입니다.
> 
> 일단은 도메인으로 접근해야 static page를 볼 수 있습니다.
> 
> > https://alpha-ka-js.github.io/HTML-CSS-ARTIST/leejehwan/chpater2/2.10.Semantic_HTML.html
> 
> 이후 index.html 생성 -> 각 user별 link or navigation bar 만들기

아니 근데 뜨네요... readme가...

**Comment by hamjins** [comment]
@LeeJehwan , 네 저도 확인해보니 그게 떠서 comment를 지웠었습니다 ㅋㅋㅋㅋ readme에 table은 이렇게 뜨는건 md 적용이 안된걸까요...? 뭘까요? ㅠㅠ
![image](https://user-images.githubusercontent.com/35097721/90380075-92d00f00-e0b6-11ea-8792-ec7664b4595d.png)

**Comment by LeeJehwan** [comment]
> @LeeJehwan , 네 저도 확인해보니 그게 떠서 comment를 지웠었습니다 ㅋㅋㅋㅋ readme에 table은 이렇게 뜨는건 md 적용이 안된걸까요...? 뭘까요? ㅠㅠ
> ![image](https://user-images.githubusercontent.com/35097721/90380075-92d00f00-e0b6-11ea-8792-ec7664b4595d.png)

심지어 제 뱃지도 적용이안됩니다 ㅠㅠ 
md파일이라 그런걸까요...! 
추후 수정할게요 ㅠㅠ

**Comment by hamjins** [comment]
> > @LeeJehwan , 네 저도 확인해보니 그게 떠서 comment를 지웠었습니다 ㅋㅋㅋㅋ readme에 table은 이렇게 뜨는건 md 적용이 안된걸까요...? 뭘까요? ㅠㅠ
> > ![image](https://user-images.githubusercontent.com/35097721/90380075-92d00f00-e0b6-11ea-8792-ec7664b4595d.png)
> 
> 심지어 제 뱃지도 적용이안됩니다 ㅠㅠ
> md파일이라 그런걸까요...!
> 추후 수정할게요 ㅠㅠ

기본적으로 github pages가 적용된 레포에 md를 지원해주나 보네요..? (내뇌망상)
+ [github pages가 좋아졌어요](https://www.devpools.kr/2016/12/11/github-page%EA%B0%80-%EC%A2%8B%EC%95%84%EC%A1%8C%EC%96%B4%EC%9A%94/) << 이 페이지 보니, 

**index.md( 또는 index.html)이 없다면 README파일을 인덱스로 사용합니다. 깃헙 리파지토리에서 파일을 브라우징할때 때랑은 다릅니다.**

라고 하네요 ㅎㅎ 

안되면 index.html을 만들어도 좋을것같아요 ㅎㅎ 고생하십니다 d^-^b

**Comment by LeeJehwan** [comment]
@hamjins 꿀정보 감사합니다~ index.html 만들기 너무재밌겠네요~   🥕🙋‍♂️🥕

내루미님도 같이 가실까요 d=====(￣▽￣*)b

**Comment by hamjins** [comment]
> @hamjins 꿀정보 감사합니다~ index.html 만들기 너무재밌겠네요~ 🥕🙋‍♂️🥕
> 
> 내루미님도 같이 가실까요 d=====(￣▽￣*)b

ㄲㄲ하시죵 ( ˃̆ૢ௰˂̆ૢഃ ) ლ

**Comment by LeeJehwan** [comment]
> > > @LeeJehwan , 네 저도 확인해보니 그게 떠서 comment를 지웠었습니다 ㅋㅋㅋㅋ readme에 table은 이렇게 뜨는건 md 적용이 안된걸까요...? 뭘까요? ㅠㅠ
> > > ![image](https://user-images.githubusercontent.com/35097721/90380075-92d00f00-e0b6-11ea-8792-ec7664b4595d.png)
> > 
> > 
> > 심지어 제 뱃지도 적용이안됩니다 ㅠㅠ
> > md파일이라 그런걸까요...!
> > 추후 수정할게요 ㅠㅠ
> 
> 기본적으로 github pages가 적용된 레포에 md를 지원해주나 보네요..? (내뇌망상)
> 
> * [github pages가 좋아졌어요](https://www.devpools.kr/2016/12/11/github-page%EA%B0%80-%EC%A2%8B%EC%95%84%EC%A1%8C%EC%96%B4%EC%9A%94/) << 이 페이지 보니,
> 
> **index.md( 또는 index.html)이 없다면 README파일을 인덱스로 사용합니다. 깃헙 리파지토리에서 파일을 브라우징할때 때랑은 다릅니다.**
> 
> 라고 하네요 ㅎㅎ
> 
> 안되면 index.html을 만들어도 좋을것같아요 ㅎㅎ 고생하십니다 d^-^b

@hamjins 늦었습니다.

깨지는 이유를 알아냈어요... table 위에 엔터 한칸을 쳐주니 안깨져요...
그리고 badge는 깨지길래 걍 html로 노가다 해줬어요
